### ISSUE TITLE
Error when train with my own data

### ISSUE THREAD

**Issue by wizholy** [allanzelener/YAD2K#106]
Traceback (most recent call last):
  File "retrain_yolo.py", line 346, in <module>
    _main(args)
  File "retrain_yolo.py", line 65, in _main
    detectors_mask, matching_true_boxes = get_detector_mask(boxes, anchors)
  File "retrain_yolo.py", line 159, in get_detector_mask
    detectors_mask[i], matching_true_boxes[i] = preprocess_true_boxes(box, ancho
rs, [416, 416])
  File "D:\projects\RCNN\YAD2K\yad2k\models\keras_yolo.py", line 420, in preproc
ess_true_boxes
    detectors_mask[i, j, best_anchor] = 1
IndexError: index 13 is out of bounds for axis 0 with size 13

D:\projects\RCNN\YAD2K>

**Comment by wizholy** [comment]
the problem has been solved.
https://github.com/allanzelener/YAD2K/issues/24#issuecomment-315803411
