### ISSUE TITLE
TypeError: buffer is too small for requested array

### ISSUE THREAD

**Issue by gbusr** [allanzelener/YAD2K#107]
thanks,I got error, How can  I  do?    

File "E:/yad2k/yad2k.py", line 156, in _main
    buffer=weights_file.read(weights_size * 4)) 
# weights_size =  28311552 TypeError: buffer is too small for requested array
TypeError: buffer is too small for requested array

**Comment by gbusr** [comment]
python3.6

**Comment by gbusr** [comment]
https://github.com/gbusr/YAD2K  
 download （wget https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolo.cfg） in  this page ，solve it。

**Comment by Estapraq** [comment]
The link is not found any replacement?

**Comment by vasanthhr** [comment]
Hello ALL,

I added this in open issue: https://github.com/allanzelener/YAD2K/issues/9

I tried to convert [this](https://github.com/azmathmoosa/azFace) weights and cfg files. And Even I tried to use new cfg files as mentioned in  https://github.com/pjreddie/darknet/tree/master/cfg . But no success and still getting the same error as mentioned below.

Used the below command for conversion:

`./yad2k.py face_config.cfg tiny-yolo-azface-fddb_82000.weights model_data/f-y2-t.h5`



Getting below error:

```
Parsing section convolutional_4
conv2d bn leaky (3, 3, 128, 256)
Parsing section maxpool_4
Parsing section convolutional_5
conv2d bn leaky (3, 3, 256, 512)
Parsing section maxpool_5
Parsing section convolutional_6
conv2d bn leaky (3, 3, 512, 1024)
2019-07-14 15:00:28.017644: W tensorflow/core/framework/allocator.cc:107] Allocation of 18874368 exceeds 10% of system memory.
2019-07-14 15:00:28.271043: W tensorflow/core/framework/allocator.cc:107] Allocation of 18874368 exceeds 10% of system memory.
2019-07-14 15:00:28.305239: W tensorflow/core/framework/allocator.cc:107] Allocation of 18874368 exceeds 10% of system memory.
Parsing section convolutional_7
conv2d bn leaky (3, 3, 1024, 1024)
2019-07-14 15:00:29.538725: W tensorflow/core/framework/allocator.cc:107] Allocation of 37748736 exceeds 10% of system memory.
2019-07-14 15:00:30.050551: W tensorflow/core/framework/allocator.cc:107] Allocation of 37748736 exceeds 10% of system memory.
Parsing section convolutional_8
conv2d    linear (1, 1, 1024, 30)
Traceback (most recent call last):
  File "./yad2k.py", line 270, in <module>
    _main(parser.parse_args())
  File "./yad2k.py", line 156, in _main
    buffer=weights_file.read(weights_size * 4))
TypeError: buffer is too small for requested array
```
