### ISSUE TITLE
TypeError: buffer is too small for requested array

### ISSUE THREAD

**Issue by xuyouze** [allanzelener/YAD2K#13]
when i run "python yad2k.py cfg/yolo.cfg yolo.weights model_data/yolo.h5" ,the yolo.weights is 194MB.

**Comment by yhcc** [comment]
You should use another yolo.cfg file. This file is different from the one generates this weight. This one https://github.com/pjreddie/darknet/blob/master/cfg/yolo.cfg may work or the yolo.2.0.cfg.

**Comment by caglorithm** [comment]
Thanks this solves the issue. A sidenote: the parser doesn't work with files that don't have a 'cfg' extension! 

AssertionError: cfg/yolo.cfg.new is not a .cfg file

I had to rename it to yolo_new.cfg lol...

**Comment by xuyouze** [comment]
Thanks， but there is another problem. 
Traceback (most recent call last):
  File "yad2k.py", line 271, in <module>
    _main(parser.parse_args())
  File "yad2k.py", line 255, in _main
    model.save('{}'.format(output_path))
  File "E:\python\lib\site-packages\keras\engine\topology.py", line 2429, in save
    save_model(self, filepath, overwrite)
  File "E:\python\lib\site-packages\keras\models.py", line 101, in save_model
    'config': model.get_config()
  File "E:\python\lib\site-packages\keras\engine\topology.py", line 2246, in get_config
    layer_config = layer.get_config()
  File "E:\python\lib\site-packages\keras\layers\core.py", line 668, in get_config
    function = func_dump(self.function)
  File "E:\python\lib\site-packages\keras\utils\generic_utils.py", line 177, in func_dump
    code = marshal.dumps(func.__code__).decode('raw_unicode_escape')
UnicodeDecodeError: 'rawunicodeescape' codec can't decode bytes in position 195-196: truncated \uXXXX


Does it matter??

**Comment by caglorithm** [comment]
Please open a new issue if you think it is a separate problem. This one should be marked closed.

**Comment by vasanthhr** [comment]
Hello ALL,

I added this in open issue: https://github.com/allanzelener/YAD2K/issues/9

I tried to convert [this](https://github.com/azmathmoosa/azFace) weights and cfg files. And Even I tried to use new cfg files as mentioned in  https://github.com/pjreddie/darknet/tree/master/cfg . But no success and still getting the same error as mentioned below.

Used the below command for conversion:

`./yad2k.py face_config.cfg tiny-yolo-azface-fddb_82000.weights model_data/f-y2-t.h5`



Getting below error:

```
Parsing section convolutional_4
conv2d bn leaky (3, 3, 128, 256)
Parsing section maxpool_4
Parsing section convolutional_5
conv2d bn leaky (3, 3, 256, 512)
Parsing section maxpool_5
Parsing section convolutional_6
conv2d bn leaky (3, 3, 512, 1024)
2019-07-14 15:00:28.017644: W tensorflow/core/framework/allocator.cc:107] Allocation of 18874368 exceeds 10% of system memory.
2019-07-14 15:00:28.271043: W tensorflow/core/framework/allocator.cc:107] Allocation of 18874368 exceeds 10% of system memory.
2019-07-14 15:00:28.305239: W tensorflow/core/framework/allocator.cc:107] Allocation of 18874368 exceeds 10% of system memory.
Parsing section convolutional_7
conv2d bn leaky (3, 3, 1024, 1024)
2019-07-14 15:00:29.538725: W tensorflow/core/framework/allocator.cc:107] Allocation of 37748736 exceeds 10% of system memory.
2019-07-14 15:00:30.050551: W tensorflow/core/framework/allocator.cc:107] Allocation of 37748736 exceeds 10% of system memory.
Parsing section convolutional_8
conv2d    linear (1, 1, 1024, 30)
Traceback (most recent call last):
  File "./yad2k.py", line 270, in <module>
    _main(parser.parse_args())
  File "./yad2k.py", line 156, in _main
    buffer=weights_file.read(weights_size * 4))
TypeError: buffer is too small for requested array
```
