### ISSUE TITLE
ValueError: Unsupported section header type: maxpool_0

### ISSUE THREAD

**Issue by carlchandev** [allanzelener/YAD2K#148]
```
$ python yad2k.py cfg/yolov2-tiny.cfg yolov2-tiny.weights  data\yolov2-tiny.h5
```

Output
```
2018-09-10 17:39:44.881414: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX
2018-09-10 17:39:44.883482: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 4. Tune using inter_op_parallelism_threads for best performance.
Using TensorFlow backend.
Loading weights.
Weights Header:  [       0        2        0 26316800        0]
Parsing Darknet config.
Creating Keras model.
Parsing section net_0
Parsing section convolutional_0
conv2d bn leaky (3, 3, 3, 16)
Parsing section maxpool_0
Traceback (most recent call last):
  File "yad2k.py", line 277, in <module>
    _main(parser.parse_args())
  File "yad2k.py", line 255, in _main
    'Unsupported section header type: {}'.format(section))
ValueError: Unsupported section header type: maxpool_0
```

Try find solution on web but no luck, any help is appreciated.

**Comment by brimalm** [comment]
Same..
