### ISSUE TITLE
Generate yolo.h5 file 

### ISSUE THREAD

**Issue by kir9-git** [allanzelener/YAD2K#186]
I get a error message when I run yad2k.py
"Traceback (most recent call last):
  File "yad2k.py", line 270, in <module>
    _main(parser.parse_args())
  File "yad2k.py", line 156, in _main
    buffer=weights_file.read(weights_size * 4))
TypeError: buffer is too small for requested array "

_Originally posted by @geserit5 in https://github.com/JudasDie/deeplearning.ai/issues/2#issuecomment-645880593_

Any suggestions?

Any workaround to run the same in CUDA ?

**Comment by kir9-git** [comment]
Any thoughts or ideas about this ?
Anybody could you share the yolo.h5 file in a shared folder ?
