### ISSUE TITLE
TypeError: Expected binary or unicode string, got Elemwise{add,no_inplace}

### ISSUE THREAD

**Issue by zaoyang** [allanzelener/YAD2K#39]
I followed your readme exactly with your environment.yaml. I got the following error. I figure it's a problem when you initially created the weights and the current weights right? Do you know what the potential issue is and if there's an easy fix? 

Parsing section reorg_0
Traceback (most recent call last):
  File "./yad2k.py", line 270, in <module>
    _main(parser.parse_args())
  File "./yad2k.py", line 236, in _main
    name='space_to_depth_x2')(prev_layer))
  File "/home/ubuntu/anaconda2/envs/yad2k/lib/python3.6/site-packages/keras/engine/topology.py", line 578, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/ubuntu/anaconda2/envs/yad2k/lib/python3.6/site-packages/keras/layers/core.py", line 659, in call
    return self.function(inputs, **arguments)
  File "/home/ubuntu/Code/YAD2K/yad2k/models/keras_yolo.py", line 32, in space_to_depth_x2
    return tf.space_to_depth(x, block_size=2)
  File "/home/ubuntu/anaconda2/envs/yad2k/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3399, in space_to_depth
    block_size=block_size, name=name)
  File "/home/ubuntu/anaconda2/envs/yad2k/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 494, in apply_op
    raise err
  File "/home/ubuntu/anaconda2/envs/yad2k/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 491, in apply_op
    preferred_dtype=default_dtype)
  File "/home/ubuntu/anaconda2/envs/yad2k/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 702, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/ubuntu/anaconda2/envs/yad2k/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 110, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/ubuntu/anaconda2/envs/yad2k/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 99, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/ubuntu/anaconda2/envs/yad2k/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 441, in make_tensor_proto
    tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
  File "/home/ubuntu/anaconda2/envs/yad2k/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 441, in <listcomp>
    tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
  File "/home/ubuntu/anaconda2/envs/yad2k/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 65, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got Elemwise{add,no_inplace}.0

**Comment by zaoyang** [comment]
this is an issue with theano

**Comment by rmmal** [comment]
How did you solved this error ??

**Comment by zaoyang** [comment]
Just change to Tensorflow
