### ISSUE TITLE
Image not found error. Really wired.

### ISSUE THREAD

**Issue by jinfagang** [allanzelener/YAD2K#42]
I run the convert yolo model to h5py model, but got this error:
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 10): Library not loaded: @rpath/libcublas.8.0.dylib
  Referenced from: /usr/local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
  Reason: image not found
```
I am using Tensorflow 1.1 and keras the newest version, macOS, I am not sure it's error about keras or tensorflow or simply about conda (I am not using Anaconda at all), could you help out what's going wrong? This prevent me dive into this very good project, I really like to try yolo-v2 on tensorflow. Many thanks.

**Comment by jinfagang** [comment]
It's my bad, I made a very stupid mistake.

**Comment by ChenLi0830** [comment]
Hi @jinfagang , I have the exact same error as yours. How did you fixed the error?

**Comment by lucasjinreal** [comment]
You should install tensorflow first.

**Comment by ChenLi0830** [comment]
Thanks @jinfagang , I ended up solving my problem by following the instructions here https://github.com/tensorflow/tensorflow/issues/6729
