### ISSUE TITLE
Where can I download the converted H5 file?

### ISSUE THREAD

**Issue by tianshangwuyun** [allanzelener/YAD2K#57]
Where can I download the converted H5 file?

**Comment by YouYouExcellent** [comment]
H5 file is created by yad2k.py

wget http://pjreddie.com/media/files/yolo.weights
wget https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolo.cfg
./yad2k.py yolo.cfg yolo.weights **model_data/yolo.h5**

**Comment by Bingohong** [comment]
on window sys, we can run _python yad2k.py yolo.cfg yolo.weights model_data/yolo.h5_ to generate the h5 file

**Comment by SaxonLord** [comment]
Or we could just download it if someone would post it...

**Comment by longzee** [comment]
someone provides the translated weigths, [link](https://pan.baidu.com/s/1dGbyycT ), code：`xgr2`
[original post](https://blog.csdn.net/hongbin_xu/article/details/78774055)

**Comment by captkkk** [comment]
python yad2k.py yolo.cfg yolo.weights yolo.h5
Using TensorFlow backend.
Traceback (most recent call last):
  File "yad2k.py", line 24, in <module>
    from yad2k.models.keras_yolo import (space_to_depth_x2,
  File "D:\KevinWong\Documents\Python\yad2k.py", line 24, in <module>
    from yad2k.models.keras_yolo import (space_to_depth_x2,
ModuleNotFoundError: No module named 'yad2k.models'; 'yad2k' is not a package

**Comment by ilyarudyak** [comment]
updated link fo v2 config:
https://github.com/pjreddie/darknet/blob/master/cfg/yolov2.cfg

**Comment by SaxonLord** [comment]
Maybe...
 yolo.h5
<https://drive.google.com/a/spragg.com/file/d/11Q0Zq_bQSusPP8ALA3yeZq9j0yMfMBe-/view?usp=drive_web>

**Comment by Antanskas** [comment]
File "C:\Users\Sony\Desktop\YOLO in keras\yad2k\yad2k.py", line 241
    print(cfg_parser[section]['anchors'], file=f)
                                              ^
SyntaxError: invalid syntax

Can domeone help me with this error?
