### ISSUE TITLE
You must feed a value for placeholder tensor

### ISSUE THREAD

**Issue by Ahziel** [allanzelener/YAD2K#62]
I'm trying to modified  YOLO to create style transfer script.To create the script, I followed a tutorial on internet but I found out that the tutorial code is basic in the source code of Keras (which you can find on Github easily)

I don't know if it's a good idea or if it's possible but I want to try because YOLO is fast compare to VGG and with my graphic card it can be cool.

When I launched my script I have an error like that

``` bash
 W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: You must feed a value for placeholder tensor 'batch_normalization_1/keras_learning_phase' with dtype bool
         [[Node: batch_normalization_1/keras_learning_phase = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: You must feed a value for placeholder tensor 'batch_normalization_1/keras_learning_phase' with dtype bool
         [[Node: batch_normalization_1/keras_learning_phase = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: You must feed a value for placeholder tensor 'batch_normalization_1/keras_learning_phase' with dtype bool
         [[Node: batch_normalization_1/keras_learning_phase = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: You must feed a value for placeholder tensor 'batch_normalization_1/keras_learning_phase' with dtype bool
         [[Node: batch_normalization_1/keras_learning_phase = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: You must feed a value for placeholder tensor 'batch_normalization_1/keras_learning_phase' with dtype bool
         [[Node: batch_normalization_1/keras_learning_phase = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: You must feed a value for placeholder tensor 'batch_normalization_1/keras_learning_phase' with dtype bool
         [[Node: batch_normalization_1/keras_learning_phase = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: You must feed a value for placeholder tensor 'batch_normalization_1/keras_learning_phase' with dtype bool
         [[Node: batch_normalization_1/keras_learning_phase = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: You must feed a value for placeholder tensor 'batch_normalization_1/keras_learning_phase' with dtype bool
         [[Node: batch_normalization_1/keras_learning_phase = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: You must feed a value for placeholder tensor 'batch_normalization_1/keras_learning_phase' with dtype bool
         [[Node: batch_normalization_1/keras_learning_phase = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: You must feed a value for placeholder tensor 'batch_normalization_1/keras_learning_phase' with dtype bool
         [[Node: batch_normalization_1/keras_learning_phase = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/usr/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
    status, run_metadata)
  File "/usr/lib64/python3.4/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/lib/python3.4/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'batch_normalization_1/keras_learning_phase' with dtype bool
         [[Node: batch_normalization_1/keras_learning_phase = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
         [[Node: gradients/AddN_81/_487 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_6518_gradients/AddN_81", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "style.py", line 165, in <module>
    x, min_val, info = fmin_l_bfgs_b(evaluator.loss, x.flatten(),fprime=evaluator.grads, maxfun=20)
  File "/usr/lib64/python3.4/site-packages/scipy/optimize/lbfgsb.py", line 188, in fmin_l_bfgs_b
    **opts)
  File "/usr/lib64/python3.4/site-packages/scipy/optimize/lbfgsb.py", line 320, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/usr/lib64/python3.4/site-packages/scipy/optimize/lbfgsb.py", line 271, in func_and_grad
    f = fun(x, *args)
  File "/usr/lib64/python3.4/site-packages/scipy/optimize/optimize.py", line 285, in function_wrapper
    return function(*(wrapper_args + args))
  File "style.py", line 142, in loss
    loss_value, grad_values = eval_loss_and_grads(x)
  File "style.py", line 129, in eval_loss_and_grads
    outs = f_outputs([x])
  File "/usr/lib/python3.4/site-packages/Keras-2.0.6-py3.4.egg/keras/backend/tensorflow_backend.py", line 2268, in __call__
  File "/usr/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'batch_normalization_1/keras_learning_phase' with dtype bool
         [[Node: batch_normalization_1/keras_learning_phase = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
         [[Node: gradients/AddN_81/_487 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_6518_gradients/AddN_81", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'batch_normalization_1/keras_learning_phase', defined at:
  File "style.py", line 63, in <module>
    yolo_body = yolo_body(image_input, len(anchors), class_names)
  File "/home/versalg/work_application/YOLO_WS/yad2k/models/keras_yolo.py", line 47, in yolo_body
    darknet = Model(inputs, darknet_body()(inputs))
  File "/home/versalg/work_application/YOLO_WS/yad2k/utils/utils.py", line 13, in <lambda>
    return reduce(lambda f, g: lambda *a, **kw: g(f(*a, **kw)), funcs)
  File "/home/versalg/work_application/YOLO_WS/yad2k/utils/utils.py", line 13, in <lambda>
    return reduce(lambda f, g: lambda *a, **kw: g(f(*a, **kw)), funcs)
  File "/home/versalg/work_application/YOLO_WS/yad2k/utils/utils.py", line 13, in <lambda>
    return reduce(lambda f, g: lambda *a, **kw: g(f(*a, **kw)), funcs)
  File "/home/versalg/work_application/YOLO_WS/yad2k/utils/utils.py", line 13, in <lambda>
    return reduce(lambda f, g: lambda *a, **kw: g(f(*a, **kw)), funcs)
  File "/home/versalg/work_application/YOLO_WS/yad2k/utils/utils.py", line 13, in <lambda>
    return reduce(lambda f, g: lambda *a, **kw: g(f(*a, **kw)), funcs)
  File "/home/versalg/work_application/YOLO_WS/yad2k/utils/utils.py", line 13, in <lambda>
    return reduce(lambda f, g: lambda *a, **kw: g(f(*a, **kw)), funcs)
  File "/home/versalg/work_application/YOLO_WS/yad2k/utils/utils.py", line 13, in <lambda>
    return reduce(lambda f, g: lambda *a, **kw: g(f(*a, **kw)), funcs)
  File "/home/versalg/work_application/YOLO_WS/yad2k/utils/utils.py", line 13, in <lambda>
    return reduce(lambda f, g: lambda *a, **kw: g(f(*a, **kw)), funcs)
  File "/home/versalg/work_application/YOLO_WS/yad2k/utils/utils.py", line 13, in <lambda>
    return reduce(lambda f, g: lambda *a, **kw: g(f(*a, **kw)), funcs)
  File "/home/versalg/work_application/YOLO_WS/yad2k/utils/utils.py", line 13, in <lambda>
    return reduce(lambda f, g: lambda *a, **kw: g(f(*a, **kw)), funcs)
  File "/home/versalg/work_application/YOLO_WS/yad2k/utils/utils.py", line 13, in <lambda>
    return reduce(lambda f, g: lambda *a, **kw: g(f(*a, **kw)), funcs)
  File "/home/versalg/work_application/YOLO_WS/yad2k/utils/utils.py", line 13, in <lambda>
    return reduce(lambda f, g: lambda *a, **kw: g(f(*a, **kw)), funcs)
  File "/usr/lib/python3.4/site-packages/Keras-2.0.6-py3.4.egg/keras/engine/topology.py", line 596, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/lib/python3.4/site-packages/Keras-2.0.6-py3.4.egg/keras/layers/normalization.py", line 190, in call
    training=training)
  File "/usr/lib/python3.4/site-packages/Keras-2.0.6-py3.4.egg/keras/backend/tensorflow_backend.py", line 2600, in in_train_phase
    training = learning_phase()
  File "/usr/lib/python3.4/site-packages/Keras-2.0.6-py3.4.egg/keras/backend/tensorflow_backend.py", line 116, in learning_phase
    name='keras_learning_phase')
  File "/usr/lib/python3.4/site-packages/tensorflow/python/ops/array_ops.py", line 1502, in placeholder
    name=name)
  File "/usr/lib/python3.4/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2149, in _placeholder
    name=name)
  File "/usr/lib/python3.4/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'batch_normalization_1/keras_learning_phase' with dtype bool
         [[Node: batch_normalization_1/keras_learning_phase = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
         [[Node: gradients/AddN_81/_487 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_6518_gradients/AddN_81", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]
```

I have searched on the internet to find a solution to my problem, but even if there are plenty of posts dealing with a similar problem, none of the solutions I have tried succeeded.

It seems that the problem occurs at this line :

```python
x,min_val,info=fmin_l_bfgs_b(evaluator.loss,x.flatten(),fprime=evaluator.grads, maxfun=20)
```

I leave you the whole of my script in the hope that it will allow you to see a little more clear.

I had some issues to import the yolo model so maybe it's linked. I will continue looking for a solution, but being a beginner, if any of you can unblock me and allow me to finish this project it would be wonderful !! You would be awesome!

```python
import h5py
import matplotlib.pyplot as plt
import numpy as np
import PIL
import tensorflow as tf
from keras import backend as K
from keras.models import Model,load_model
from keras.layers import Input, Lambda, Conv2D
from scipy.optimize import fmin_l_bfgs_b
from scipy.misc import imsave


from yad2k.models.keras_yolo import (preprocess_true_boxes, yolo_body,
                                     yolo_eval, yolo_head, yolo_loss)

height = 416
width = 416
class_names = 30

anchors = np.array(
    ((0.57273, 0.677385), (1.87446, 2.06253), (3.33843, 5.47434),
     (7.88282, 3.52778), (9.77052, 9.16828)))

content_image_path = 'Image/me3.jpg'
content_image = Image.open(content_image_path)
heightOr, widthOr = content_image.size
content_image = content_image.resize((height, width), PIL.Image.BICUBIC)

style_image_path = 'Image/mosaic1.jpg'
style_image = Image.open(style_image_path)
style_image = style_image.resize((height, width), PIL.Image.BICUBIC)

content_array = np.asarray(content_image, dtype=np.float)
content_array = np.expand_dims(content_array, axis=0)
print(content_array.shape)

style_array = np.asarray(style_image, dtype=np.float)
style_array = np.expand_dims(style_array, axis=0)
print(style_array.shape)

content_image = K.variable(content_array)
style_image = K.variable(style_array)
combination_image = K.placeholder((1, height, width, 3))

input_tensor = K.concatenate([content_image,style_image,combination_image], axis=0)

#Get the model

image_input = Input(tensor=input_tensor)
yolo_body = yolo_body(image_input, len(anchors), class_names)
topless_yolo = Model(yolo_body.input, yolo_body.layers[-2].output)

topless_yolo_path = os.path.join('model_data', 'yolo_topless.h5')
topless_yolo.load_weights(topless_yolo_path)

final_layer = Conv2D(len(anchors)*(5+class_names), (1, 1), activation='linear')(topless_yolo.output)

yolo_model = Model(image_input, final_layer)

layers = dict([(layer.name, layer.output) for layer in yolo_model.layers])

content_weight = 0.025
style_weight = 5.0
total_variation_weight = 1.0

loss = K.variable(0.)

def content_loss(content, combination):
    return K.sum(K.square(combination - content))


layer_features = layers['conv2d_5']
content_image_features = layer_features[0, :, :, :]
combination_features = layer_features[2, :, :, :]

loss += content_weight * content_loss(content_image_features,
                                      combination_features)

def gram_matrix(x):
    features = K.batch_flatten(K.permute_dimensions(x, (2, 0, 1)))
    gram = K.dot(features, K.transpose(features))
    return gram

def style_loss(style, combination):
    S = gram_matrix(style)
    C = gram_matrix(combination)
    channels = 3
    size = height * width
    return K.sum(K.square(S - C)) / (4. * (channels ** 2) * (size ** 2))

feature_layers = ['conv2d_2', 'conv2d_5',
                  'conv2d_9', 'conv2d_12',
                  'conv2d_15']
for layer_name in feature_layers:
    layer_features = layers[layer_name]
    style_features = layer_features[1, :, :, :]
    combination_features = layer_features[2, :, :, :]
    sl = style_loss(style_features, combination_features)
    loss += (style_weight / len(feature_layers)) * sl

def total_variation_loss(x):
    a = K.square(x[:, :height-1, :width-1, :] - x[:, 1:, :width-1, :])
    b = K.square(x[:, :height-1, :width-1, :] - x[:, :height-1, 1:, :])
    return K.sum(K.pow(a + b, 1.25))

loss += total_variation_weight * total_variation_loss(combination_image)

grads = K.gradients(loss, combination_image)

outputs = [loss]
outputs += grads
f_outputs = K.function([combination_image], outputs)

def eval_loss_and_grads(x):
    x = x.reshape((1, height, width, 3))
    outs = f_outputs([x])
    loss_value = outs[0]
    grad_values = outs[1].flatten().astype('float64')
    return loss_value, grad_values

class Evaluator(object):

    def __init__(self):
        self.loss_value = None
        self.grads_values = None

    def loss(self, x):
        assert self.loss_value is None
        loss_value, grad_values = eval_loss_and_grads(x)
        self.loss_value = loss_value
        self.grad_values = grad_values
        return self.loss_value

    def grads(self, x):
        assert self.loss_value is not None
        grad_values = np.copy(self.grad_values)
        self.loss_value = None
        self.grad_values = None
        return grad_values

evaluator = Evaluator()

x = np.random.uniform(0, 255, (1, height, width, 3)) - 128.

iterations = 10

K.set_learning_phase(1)

for i in range(iterations):
    print('Start of iteration', i)
    start_time = time.time()
    x, min_val, info = fmin_l_bfgs_b(evaluator.loss, x.flatten(),fprime=evaluator.grads, maxfun=20)
    print('Current loss value:', min_val)
    end_time = time.time()
    print('Iteration %d completed in %ds' % (i, end_time - start_time))

Image.fromarray(x).resize((heightOr,widthOr)).save("result.jpg")
```

A big thank you for your attention !

**Comment by huangguojie880** [comment]
Try to import K and set learning phase before your model.

from keras import backend as K

K.set_learning_phase(1) #set learning phase
