### ISSUE TITLE
Quick Start: Anchor file is None

### ISSUE THREAD

**Issue by kuonangzhe** [allanzelener/YAD2K#64]
Thanks for the great work! I firstly tried with the tiny-yolo, which worked fine. Then I wanted to follow the quick start to see how is the normal yolo2 on coco. However, after I transfer the weight and cfg into h5, and run the ./test_yolo.py, I got the error, which then turned out that the anchor file was actually nothing inside.

Here is the error message:
Traceback (most recent call last):
  File "./test_yolo.py", line 200, in <module>
    _main(parser.parse_args())
  File "./test_yolo.py", line 77, in _main
    anchors = [float(x) for x in anchors.split(',')]
  File "./test_yolo.py", line 77, in <listcomp>
    anchors = [float(x) for x in anchors.split(',')]
ValueError: could not convert string to float: 
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f0bca06ff98>>
Traceback (most recent call last):
  File "/home/czm/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 595, in __del__
TypeError: 'NoneType' object is not callable

The related anchor file was 0 bytes.

Thanks for the help!

**Comment by ACfromecs** [comment]
Hi, I got same error and solved by make anchors file from .cfg file used before.
You can do it by following command:
`grep anchors yolo.cfg > model_data/yolo_anchors.txt`
`sed -i 's/anchors//g' model_data/yolo_anchors.txt`
`sed -i 's/=//g' model_data/yolo_anchors.txt`

**Comment by sojohan** [comment]
Hi Yolo
When I run:
python yad2k.py yolo.cfg yolo.weights model_data/yolo.h5

I get the file yolo_anchors.txt in the model_data but it has 0 size. What should it be?
Is it possible to generate it correctly from within python?
Thanks

**Comment by JyoHuang** [comment]
as mention by @ACfromecs 
grep anchors yolo.cfg > model_data/yolo_anchors.txt

sed -i 's/anchors//g' model_data/yolo_anchors.txt
sed -i 's/=//g' model_data/yolo_anchors.txt
if sed -I .... get Error
just remove "anchors" and "=" in the file "yolo_anchors.txt"

and it works ^_^

**Comment by satishtilwani123** [comment]
can you please tell us how to run these commands if we use the folder in google colab

**Comment by Sivabanu** [comment]
Can you please tell me how to run these on windows command line
