### ISSUE TITLE
retrain help

### ISSUE THREAD

**Issue by yochananscharf** [allanzelener/YAD2K#70]
## Error when trying to retrain using code based on [https://github.com/shadySource](url)

```
python retrain_yolo.py 
Using TensorFlow backend.
Traceback (most recent call last):
  File "retrain_yolo.py", line 345, in <module>




    _main(args)
  File "retrain_yolo.py", line 64, in _main
    detectors_mask, matching_true_boxes = get_detector_mask(boxes, anchors)
  File "retrain_yolo.py", line 158, in get_detector_mask
    detectors_mask[i], matching_true_boxes[i] = preprocess_true_boxes(box, anchors, [416, 416])
  File "path/keras_yolo.py", line 420, in preprocess_true_boxes
    detectors_mask[i, j, best_anchor] = 1
IndexError: index 13 is out of bounds for axis 1 with size 13
```

**Comment by yochananscharf** [comment]
[https://github.com/allanzelener/YAD2K/issues/24#issuecomment-315803411](url) solved the problem.
Thanks
